In [ ]:
!nvidia-smi

Wed Oct 13 19:58:42 2021
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 470.74       Driver Version: 460.32.03    CUDA Version: 11.2     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                               |                      |               MIG M. |
|===============================+======================+======================|
|   0  Tesla P100-PCIE...  Off  | 00000000:00:04.0 Off |                    0 |
| N/A   47C    P0    29W / 250W |      0MiB / 16280MiB |      0%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+

+-----------------------------------------------------------------------------+
| Processes:                                                                  |
|  GPU   GI   CI        PID   Type   Process name                  GPU Memory |
|        ID   ID                                                   Usage      |
|=============================================================================|
|  No running processes found                                                 |
+-----------------------------------------------------------------------------+

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

In [ ]:
!pip install transformers

In [ ]:
from transformers import GPT2Tokenizer, GPT2LMHeadModel
from transformers import TextDataset, DataCollatorForLanguageModeling
from transformers import TrainingArguments, Trainer,  get_cosine_schedule_with_warmup
import torch
import json
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from sklearn.model_selection import train_test_split
import re


from IPython.display import clear_output
clear_output()

___________________________

In [ ]:
df = pd.read_csv("/content/drive/MyDrive/aiijc/wiki_movie_plots_deduped (1).csv")

In [ ]:
df.Genre.value_counts()

unknown                       6083
drama                         5964
comedy                        4379
horror                        1167
action                        1098
                              ...
action / war / adventure         1
fantasy / adventure / kids       1
biography drama                  1
south african western            1
crime thriller, neo-noir         1
Name: Genre, Length: 2265, dtype: int64

In [ ]:
df = df[df.Genre == 'comedy']
df.head()

    Release Year  ...                                               Plot
7           1904  ...  The film is about a family who move to the sub...
14          1907  ...  Before heading out to a baseball game at a nea...
15          1907  ...  The plot is that of a black woman going to the...
18          1908  ...  A young couple decides to elope after being ca...
29          1910  ...  Hemlock Hoax is a detective who has little res...

[5 rows x 8 columns]

In [ ]:
df = df.dropna()

In [ ]:
df.Genre.value_counts()

comedy    4347
Name: Genre, dtype: int64

In [ ]:
df.rename(columns = {'Genre':'genre'}, inplace = True)
df.genre.value_counts()

comedy    4347
Name: genre, dtype: int64

In [ ]:
bos_token = '<BOS>'
eos_token = '<EOS>'
title_token = '<TITLE>'

def build_dataset(df, path):
    f = open(path, 'w')
    data = ''
    summaries = df['Plot'].tolist()
    titles = df['Title'].tolist()
    for i in range(len(summaries)):
        summary = str(summaries[i]).strip()
        title = titles[i]
        summary = re.sub(r"\s", " ", summary)
        data += title_token + ' ' + title + ' ' + bos_token + ' ' + summary + ' ' + eos_token + '\n'
        
    f.write(data)

In [ ]:
build_dataset(df, 'train.txt')

In [ ]:
model_name = "gpt2-large"

special_tokens_dict = {'bos_token': '<BOS>', 'eos_token': '<EOS>', 'pad_token': '<PAD>'}

tokenizer = GPT2Tokenizer.from_pretrained(model_name,
                                          truncation=True,
                                          padding=True)

num_added_toks = tokenizer.add_special_tokens(special_tokens_dict)

model = GPT2LMHeadModel.from_pretrained(model_name)

model.resize_token_embeddings(len(tokenizer))
model = model.to('cuda')

Downloading:   0%|          | 0.00/0.99M [00:00<?, ?B/s]

Downloading:   0%|          | 0.00/446k [00:00<?, ?B/s]

Downloading:   0%|          | 0.00/1.29M [00:00<?, ?B/s]

Downloading:   0%|          | 0.00/666 [00:00<?, ?B/s]

Downloading:   0%|          | 0.00/3.02G [00:00<?, ?B/s]

In [ ]:
learning_rate = 2e-5
batch_size = 1
num_epochs = 2

block_size = 256
train_dataset = TextDataset(tokenizer=tokenizer,
                            file_path= 'train.txt',
                            block_size=block_size,
                            overwrite_cache=True)


data_collator = DataCollatorForLanguageModeling(tokenizer=tokenizer, mlm=False)

/usr/local/lib/python3.7/dist-packages/transformers/data/datasets/language_modeling.py:58: FutureWarning: This dataset will be removed from the library soon, preprocessing should be handled with the 🤗 Datasets library. You can have a look at this example script for pointers: https://github.com/huggingface/transformers/blob/master/examples/pytorch/language-modeling/run_mlm.py
  FutureWarning,

In [ ]:
seed = 42
training_args = TrainingArguments(
    output_dir='stories_output',
    overwrite_output_dir=True,
    do_train=True,
    save_steps=5000, 
    num_train_epochs=num_epochs,
    per_device_train_batch_size=batch_size,
    prediction_loss_only=True,
    logging_steps=100,
    seed=seed,
    learning_rate=learning_rate
)

In [ ]:
trainer = Trainer(
    model=model,
    tokenizer=tokenizer,
    args=training_args,
    data_collator=data_collator,
    train_dataset=train_dataset
)

In [ ]:
train_dataloader = trainer.get_train_dataloader()
num_train_steps = len(train_dataloader) * num_epochs
trainer.create_optimizer_and_scheduler(num_train_steps)

trainer.lr_scheduler = get_cosine_schedule_with_warmup(
    trainer.optimizer,
    num_warmup_steps=num_train_steps // 10,
    num_training_steps=num_train_steps
)

In [ ]:
trainer.train()

***** Running training *****
  Num examples = 7902
  Num Epochs = 2
  Instantaneous batch size per device = 1
  Total train batch size (w. parallel, distributed & accumulation) = 1
  Gradient Accumulation steps = 1
  Total optimization steps = 15804

Saving model checkpoint to stories_output/checkpoint-5000
Configuration saved in stories_output/checkpoint-5000/config.json
Model weights saved in stories_output/checkpoint-5000/pytorch_model.bin
tokenizer config file saved in stories_output/checkpoint-5000/tokenizer_config.json
Special tokens file saved in stories_output/checkpoint-5000/special_tokens_map.json
added tokens file saved in stories_output/checkpoint-5000/added_tokens.json
Saving model checkpoint to stories_output/checkpoint-10000
Configuration saved in stories_output/checkpoint-10000/config.json
Model weights saved in stories_output/checkpoint-10000/pytorch_model.bin
tokenizer config file saved in stories_output/checkpoint-10000/tokenizer_config.json
Special tokens file saved in stories_output/checkpoint-10000/special_tokens_map.json
added tokens file saved in stories_output/checkpoint-10000/added_tokens.json
Saving model checkpoint to stories_output/checkpoint-15000
Configuration saved in stories_output/checkpoint-15000/config.json
Model weights saved in stories_output/checkpoint-15000/pytorch_model.bin
tokenizer config file saved in stories_output/checkpoint-15000/tokenizer_config.json
Special tokens file saved in stories_output/checkpoint-15000/special_tokens_map.json
added tokens file saved in stories_output/checkpoint-15000/added_tokens.json


Training completed. Do not forget to share your model on huggingface.co/models =)

TrainOutput(global_step=15804, training_loss=3.0086452349684745, metrics={'train_runtime': 6893.1748, 'train_samples_per_second': 2.293, 'train_steps_per_second': 2.293, 'total_flos': 1.71961372901376e+16, 'train_loss': 3.0086452349684745, 'epoch': 2.0})

In [ ]:
model.eval()

def generate(prompt):
    input_ids = tokenizer.encode(prompt, return_tensors='pt')
    input_ids = input_ids.to('cuda') 
    eos_id = tokenizer.encode(eos_token)[0]

    sample_outputs = model.generate(
        input_ids, 
        max_length=900, 
        min_length=1000,
        do_sample=True, 
        top_k=0,
        top_p=0.92, 
        temperature=0.85,
        eos_token_id=eos_id,
        num_return_sequences=3,
        pad_token_id=tokenizer.eos_token_id,
        repition_penalty=1.5)
    for i, sample_output in enumerate(sample_outputs):
          print("{}: {}\n----------------\n".format(i+1, tokenizer.decode(sample_output, skip_special_tokens=True)))

In [ ]:
title = 'The show'

prompt = title_token + ' ' + title + ' ' + bos_token

generate(prompt)

1: <TITLE> The showLa Rueff (Tony Curtis) is a young man who dreams of being an actress. He works as a waitress in an obscure diner. One day, he meets a beautiful young man, Sabine (Joan Blondell), and falls for her. After she leaves, he goes to a nightclub to find her. There he meets an uncredited but excellent actor, Bob (Brian Doyle-Murray), who plays a role in a film that is set in the same diner where La Rueff works. Sabine introduces La Rueff to her family, who are all actors. Sabine's sister, Marissa (Joan Blondell), has been a minor Hollywood star for several years. La Rueff has been getting advice from Marissa's agent and learns that Marissa wants to marry a man named Rudy (Lance Kinsey), who is a porn star. Rudy is not in the mood for a relationship, but La Rueff confides in Sabine that he is going to New York City to audition for a film.  La Rueff goes to New York City, auditioning for a part in a pornographic film. He is only hired for a cameo in the film. During the audition, Sabine's father, Jean (Steve Martin), arrives and discovers that Sabine is dating Rudy, who is scheduled to appear in the film.  When La Rueff arrives in New York, he meets Rudy, who helps him understand what Sabine is trying to do. Rudy has recently been released from prison and wants to make a comeback as a pornographic star, but has not yet found a distributor. La Rueff helps Rudy find one, and they form a romantic relationship. After meeting Rudy in an Italian restaurant, Sabine's mother (Joan Blondell) comes to New York. She says she knows La Rueff is an actor and is jealous, but she is also interested in Rudy. After La Rueff and Rudy get a meeting, Sabine's father asks La Rueff to go to the studio where Rudy is shooting his next film. La Rueff visits Rudy and they have dinner together.  Sabine and Rudy have a talk about what La Rueff has not done to make her jealous. Sabine tells him that she is in love with Rudy. Rudy tells La Rueff that she wants to marry him, but she has to run away with Sabine's father, Jean, to avoid being a gossip. She is upset that La Rueff does not know who she is. La Rueff does not want to lose Sabine, and he agrees to take her to New York. Sabine tells Rudy that she is in love with him.  Sabine goes to New York, with Rudy by her side. Rudy has another film coming out, which is set in the same diner. After a while, Sabine and Rudy fall in love with each other. However, La Rueff is not in the mood for a relationship and she tells Rudy to end their relationship. They have a talk, and Sabine admits to Rudy that she loves him. Rudy does not respond, but then Sabine tells him that she is going to New York to tell her father that she loves him. She goes to La Rueff's apartment, and they have sex.  La Rueff's father, Jean (Brian Doyle-Murray), is furious, because Sabine is not a proper actress. He tells La Rueff that she should go away and he will find someone to help her. She tells him that she loves him, but he does not believe her. Sabine tells her father she will go. When he tells Sabine that she is going to New York, she tells him that she is going to tell her father. He tells her that she is a good actress and they are going to try to find someone who will help her become an actress. She tells her father that she loves Rudy. Later, La Rueff goes to the airport and meets Rudy. The film ends with Sabine and Rudy having sex in a hotel bathroom, and Sabine calling her father for the last time. At the airport, La Rueff's father is furious. La Rueff tells his father that Sabine has been cheated, and she is gone. He also tells La Rueff to get out. La Rueff calls Sabine.  Meanwhile, Sabine's father decides that he wants to divorce her
----------------

2: <TITLE> The showRick (Simon Thompson) and Laura Ann (Jessica Walter) are a couple from the small town of Fishers, Ohio, who spend much of their time traveling to different states in search of the perfect man. When they find the perfect man in the form of Jeff (Gregory Peck), the town's newspaper publisher, the couple travel to California, hoping to find the man who will make their idyllic life a reality.  The journey is not without its problems. Rick is constantly doing research on prospective husbands, while Laura's numerous hiccups prove to be a constant distraction. At one point, a drunken Rick attempts to get home early from a date with a socialite (Claire Forlani). Rick's trip becomes a public relations disaster when his drunken behavior is caught on film and is shown on television. Laura, feeling guilty about the incident, returns home to try to put things right with her family. Meanwhile, Rick's mother, Mrs. Fisher (Kim Cattrall), gives a speech about the evils of television, during which Rick interrupts.  At a later dinner, Rick is asked to leave the house by his mother. After a brief altercation, Rick and Laura agree to go on an adventure together. They take a train to the small town of La Salle, Illinois, and begin their search by renting a cheap motel. When they arrive, Rick accidentally discovers a dinner date for Laura, played by Karen Strasser. Upon learning that Laura is engaged to Jim Jones (Charles Ruggles), a local circus performer, Rick is upset, but Laura calms him down by explaining that she is engaged to someone else and that she will miss him.  The next morning, they begin to realize how lonely they are, as well as the miserable arrangement they have with their various girlfriends. They are visited by the mayor (Peter Falk), who urges them to return to Fishers to finish their search. Rick and Laura decide to follow him, but Laura is forced to change her mind at the last minute when the mayor confronts them and insists that they stay in town. Upon their arrival, they meet the Joneses, who are extremely wealthy and well-connected. After a short while, the Joneses' wealthy cousins arrive and begin to treat them as if they were their own family.  When they go to the Joneses' home, they are surprised to learn that they are not their family, but rather, were created by an insurance company. Realizing the horror of this situation, Rick and Laura return to Fishers. After being encouraged by the Joneses to seek out the town's only doctor (who happened to be a doctor), they discover that Laura's hiccups are from stress, and they realize the source of the problem. When they arrive, they find the Joneses' home to be a mansion, complete with a swimming pool. Before the Joneses can tell them that they have been chosen for a special trip, Rick decides to tell them the truth, only to have his mother arrive and inform them that the Joneses have a daughter, and the Joneses see no reason to take her in. The Joneses try to convince Laura that the Joneses are just using her, but when she does not want to go along, they offer to let her stay with them. The Joneses' daughters turn out to be more than the Joneses had expected, and Laura ultimately decides to stay with them.  Meanwhile, Laura's fiancé, Miles (Bradley Whitford), gets engaged to the town's sheriff, Bruce (John Heard). Bruce wants to take Laura on a vacation with him, but Rick refuses. Bruce decides to take Laura with him and they take a train to Fishers, where Laura is finally allowed to be with Miles. Rick goes to a local bar to find Laura. He meets a woman who appears to be the Joneses' maid, played by Sarah Jessica Parker. She initially takes Rick's offer to stay with her, but Laura storms off. She runs into Laura's former fiancé, Jeff, who she has not seen in three years. She wants to marry him, but Rick tells her that he will only marry her if she agrees to stay with him. She agrees, and they get to know each other better.  Later, after Rick accidentally discovers Laura's brother, Trevor (Brian Keith), looking for her, the two begin to see each other
----------------

3: <TITLE> The showThe film opens with the music video for "Relax", a song by the band Korn. The film then opens with a publicity photo of Simon "Sasha" Sinclair, then closes with a still shot of Simon from a previous film. After Simon sees the photo, he tells Spike about it. Spike tells Simon that Simon is insane, that he is writing a film about sex and selling it to Hollywood. Simon leaves to get a drink at the bar, and as he leaves, he is hit by a car while trying to get out of the way of a speeding car. Simon's head is severely injured, and he is taken to the hospital.  Spike visits Simon at the hospital. Simon confesses to having a boyfriend who is attempting suicide, and suggests that Spike go to the hospital with him. They find the boyfriend unconscious and lying on a gurney. As Simon and Spike are being taken to the hospital, the boyfriend tells them that his life is in danger because his mother is Jewish, and his family will be punished if he talks about it. The boyfriend tells them that the mother is Jewish, too. The boyfriend says that Simon should be there, as he was able to save his father from being killed by a Russian mobster. Simon tells Spike that he feels terrible for him, and that he is not crazy. The boyfriend then tells them that he wanted to kill himself, and after he did, the Russians came and killed him. Simon asks Spike to come back to the hospital and tell them what happened. Spike agrees, and the two men meet with Simon's girlfriend to inform her that he is crazy.  As they are talking, Spike accidentally opens the door to Simon's apartment. Simon sees Spike and tells Spike to leave. Spike follows Simon and the two men to the apartment, where Simon tells Simon that he and his girlfriend are going to get married, and that he is planning on selling the film to Hollywood. Spike and Simon get into Simon's car to drive off, but they crash into a police car, and are arrested. They then go to the police station and are shown their mug shots. The film has been renamed The Island of Dr. Moreau, and Spike's character is named Dr. Robert Moreau. Spike is then arrested for hitting a police car. Spike and Simon get into a fight with the police officer who is trying to arrest them. The movie ends with the two men being given prison sentences of one year.  The film's opening title is followed by a close-up of Simon in a hospital, and the title card says: "Welcome to the Jungle."  In an interview, Simon says that he made the film because he was depressed and wanted to get away from his mother, who is Jewish, and she wrote him a letter, saying that she was going to kill herself. She came to see Simon and his mother for a divorce, but his mother was not interested in the divorce. After the film's ending credits roll, a still shot of Simon from the previous film appears. In the credits, it says Simon and Spike were in a relationship for two months before the film began, and that Simon is now single. The movie ends with a still shot of Simon with Spike on a beach.  In a post-credits scene, Spike and Simon are shown on a cruise ship, and in the post-credits scene, Spike and Simon are shown sleeping on a beach, together.  The film is released worldwide. Spike and Simon meet again and end up having sex. In a post-credits scene, Simon has to run from a helicopter in the jungle. Spike's character shows up and shoots Simon, but Simon is not hurt. Simon then jumps into the water and swims to shore. The film ends with Simon walking on a beach with his wedding band on his arm. In the post credits, Simon's character turns out to be a middle-aged man, and Simon is shown to be a male model. In the post-credits scene, Simon and Spike are shown dancing together on a beach. The film ends with the credits being repeated.  In a flashback, Simon was once a newscaster who had been fired for his outspoken opinions. The next morning, he is shown performing live on a local radio show, and in his opening monologue, he begins by telling his listeners about a story he tells about a man named
----------------